### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by kjnilsson** [supherman/riemann-docker-health#2]
Hi - would you mind including a license file for this project as without one noone can actually make use of it? Unless this is on purpose.

Many thanks.

**Comment by supherman** [comment]
Sorry for the late answer, I'll do it for sure

**Comment by supherman** [comment]
acdd673ad381e85d3ef91988c9b1aa3598142bd3

**Comment by kjnilsson** [comment]
Awesome. Many thanks. :)
